### ISSUE TITLE
Do something better with tags

### ISSUE THREAD

**Issue by jacobian** [jacobian/pinboard-to-sqlite#3]
Right now tags are just stored as plain text. This makes doing things like tag intersections ("find everything tagged 'django' + 'testing'") or aggregation ("what are my most common tags?") difficult.

In Postgres I would use an array field, but I don't think sqlite supports that. This could be a `tags` table and a many-to-many, but that's just clunky in a different way.

**Comment by simonw** [comment]
You can use JSON arrays in a TEXT column and Datasette can facet by them: https://datasette.readthedocs.io/en/stable/facets.html#facet-by-json-array

Demo: https://latest.datasette.io/fixtures/facetable?_facet_array=tags#facet-tags
